### ISSUE TITLE
Add Contributing Guidelines

### ISSUE THREAD

**Issue by steven-isbell** [mariohoyos92/express-open-graph-middleware#2]
Have you considered adding any guidelines on how to contribute to the development of this tool? Maybe a PR template, forking, testing, a prettier file to match formatting? Just to make sure that contributors are on the same page and the project moves in the direction you want it. Just a thought!

**Comment by mariohoyos92** [comment]
This is a terrific idea. If you can't tell, this is my first serious attempt at an open source project. Will get to it soon as I can!

**Comment by mariohoyos92** [comment]
Hello @steven-isbell ! Would you mind looking over the changes in the PR above and providing feedback? I went ahead and added formatting, linting, and testing scripts in addition to contribution guidelines, an issue template, and a pull_request template. Learning quite a bit about OSS in the process lol

**Comment by mariohoyos92** [comment]
fixed in #3
